#!/bin/bash
# chkconfig: 3 20 80
# description: RECOMMERCE!!!
start(){
        echo "Starting emporyou..."
        /bin/sh /root/emporyou/postreboot.txt &
        echo "Started emporyou..."
}

stop(){
        echo "Stopping emporyou... (doing nothing)"
        
}

restart(){
        stop
        # give stuff some time to stop before we restart
        sleep 30
        # protect against any services that can't stop before we restart (warning this kills all Java instances running as 'jboss' user)
        # if the 'su -l ...' command fails try:
        #   sudo -u jboss killall java
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo "Usage: jboss {start|stop|restart}"
        exit 1
esac

exit 0
